---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
activity <- read.csv(file="C:/Users/Zachary/Desktop/activity.csv")


## What is mean total number of steps taken per day?
## Calculate the total number of steps taken per day
stepsPerDay <- tapply(activity$steps, activity$date, sum)

## Make a histogram of the total number of steps taken each day
hist(stepsPerDay, xlab="Number of Steps", main="Histogram: Steps per Day")

## Calculate and report the mean and median of the total number of steps taken per day
meanPerDay <- mean(stepsPerDay, na.rm=TRUE)
medianPerDay <- median(stepsPerDay, na.rm=TRUE)

The mean and median number of steps per day are 1.076618910^[4] and 10765 


## What is the average daily activity pattern?
## Make a time series plot of the 5-minute interval and the average number of steps taken, averaged across all dats
stepsPerInterval <- tapply(activity$steps, activity$date, sum)
plot(as.numeric(names(stepsPerInterval)), stepsPerInterval, xlab="Interval", ylab="Steps", main="Average Daily Activity Pattern", type='l')

## Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
maxInterval <- names(sort(stepsPerInterval, decreasing = TRUE)[1])
maxSteps <- sort(stepsPerInterval, decreasing = TRUE)[1]

The interval associated with maxiumum activity is interval 835, at 206.1698113 steps

## Imputing missing values

## Calulate and report the total number of missing values in the dataset
NA.vals <- sum(is.na(activity$steps))

There are 2304 missing values in this data set

## Devise a strategy for filling in all of the missing values in the dataset

I'll fill in missing data with the mean number of steps across all days with available data for that particular interval

## Create a new dataset that is equal to the original dataset but with the missing data filled in
stepsPerInterval <- tapply(activity$steps, activity$interval, mean, na.rm=TRUE)
activity.split <- split(activity, activity$interval)
for (i in 1:length(activity.split)) {
     activity.split[[i]]$steps[is.na(activity.split[[i]]$steps)] <- stepsPerInterval[i]
    }
activity.imputed <- do.call("rbind", activity.split)
activity.imputer <- activity.imputed[order(activity.imputed$date) ,]

## Make a histogram of the total number of steps taken each day and calculate and report the mean and median total number of steps taken per day.
stepsPerDay.imputed <- tapply(activity.imputed$steps, activity.imputed$date, sum)
hist(stepsPerDay.imputed, xlab="Number of Steps", main="Histogram: Steps per Day (Imputed Data)")

meanPerDay.imputed <- mean(stepsPerDay.imputed, na.rm = TRUE)
medianPerDay.imputed <- median(stepsPerDay.imputed, na.rm = TRUE)

The mean and median number of steps per day including imputed data are 1.076618910^[4] and 1.076618910^[4]. The mean remains the 
same as prior to imputation, while the median value increased slightly


## Are there differences in activity patterns between weekdays and weekends?

## Create a new factor variable in the dataset with two levels - "weekday" and "weekend" indicating whether a given date is a weekday or weekend day.
activity.imputed$day <- ifelse(weekdays(as.Date(activity.imputed$date)) == "Saturday" | weekdays(as.Date(activity.imputed$date)) == "Sunday", "weekend", "weekday")

## Make a panel plot containing a time series plot of the 5-minute interval and the average number of steps taken, averaged across all weekday days or weekend days
stepsPerInterval.weekend <- tapply(activity.imputed[activity.imputed$day == "weekend" ,]$steps, activity.imputed[activity.imputed$day == "weekend" ,]$interval, mean, na.rm = TRUE)
stepsPerInterval.weekday <- tapply(activity.imputed[activity.imputed$day == "weekday" ,]$steps, activity.imputed[activity.imputed$day == "weekday" ,]$interval, mean, na.rm = TRUE)

### Set a 2 panel plot
par(mfrow=c(1,2))

### Plot weekday activity
plot(as.numeric(names(stepsPerInterval.weekday)), stepsPerInterval.weekday, xlab="Interval", ylab="Steps", main="Activity Pattern (Weekdays)", type="l")

### Plot weekend activity
plot(as.numeric(names(stepsPerInterval.weekend)), stepsPerInterval.weekend, xlab="Interval", ylab="Steps", main="Activity Pattern (Weekends)", type="l")
